# Generated by Django 6.0.4 on 2026-07-25 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'categoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                'db_table': 'compra',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FacturaCliente',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_comprobante', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('impuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'factura_cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_contacto', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('tipo_proveedor', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'proveedor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('rol', models.CharField(blank=True, max_length=50, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Beneficiocliente',
            fields=[
                ('id_beneficio', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('frecuencia', models.CharField(blank=True, max_length=50, null=True)),
                ('condicion', models.TextField(blank=True, null=True)),
                ('restricciones', models.TextField(blank=True, null=True)),
                ('porcentajedescuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('id_cliente', models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.cliente')),
            ],
            options={
                'db_table': 'beneficiocliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FacturaProveedor',
            fields=[
                ('id_factura_proveedor', models.AutoField(primary_key=True, serialize=False)),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo_comprobante', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_emision', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('impuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('id_compra', models.ForeignKey(blank=True, db_column='id_compra', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.compra')),
            ],
            options={
                'db_table': 'factura_proveedor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('precio_venta', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('unidad_medida', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_categoria', models.ForeignKey(blank=True, db_column='id_categoria', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoria')),
                ('id_proveedor', models.ForeignKey(blank=True, db_column='id_proveedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.proveedor')),
            ],
            options={
                'db_table': 'producto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.AutoField(primary_key=True, serialize=False)),
                ('stock_actual', models.IntegerField(blank=True, null=True)),
                ('stock_minimo', models.IntegerField(blank=True, null=True)),
                ('stock_maximo', models.IntegerField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto')),
            ],
            options={
                'db_table': 'inventario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id_devolucion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('cantidad', models.IntegerField(default=1)),
                ('plazo', models.IntegerField(blank=True, null=True)),
                ('condiciones', models.TextField(blank=True, null=True)),
                ('restricciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('id_factura', models.ForeignKey(blank=True, db_column='id_factura', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.facturacliente')),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto')),
            ],
            options={
                'db_table': 'devolucion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_detallecompra', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('id_compra', models.ForeignKey(blank=True, db_column='id_compra', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.compra')),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto')),
            ],
            options={
                'db_table': 'detalle_compra',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='id_proveedor',
            field=models.ForeignKey(blank=True, db_column='id_proveedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.proveedor'),
        ),
        migrations.CreateModel(
            name='ProductoDanado',
            fields=[
                ('id_producto_danado', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('motivo_dano', models.TextField(blank=True, null=True)),
                ('estado_proceso', models.CharField(default='PENDIENTE', max_length=30)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_devolucion', models.ForeignKey(db_column='id_devolucion', on_delete=django.db.models.deletion.DO_NOTHING, to='core.devolucion')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuario')),
            ],
            options={
                'db_table': 'producto_danado',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_movimiento', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuario')),
            ],
            options={
                'db_table': 'movimiento_inventario',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='compra',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuario'),
        ),
        migrations.CreateModel(
            name='AuditoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Correo del usuario', max_length=100)),
                ('evento', models.CharField(help_text='Tipo de evento/acción realizado', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Detalle adicional', null=True)),
                ('modulo', models.CharField(blank=True, help_text='Módulo relacionado', max_length=50, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, db_column='usuario_id', help_text='Usuario que realizó la acción', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usuario')),
            ],
            options={
                'db_table': 'auditoria_evento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Correo usado para el login', max_length=100)),
                ('exito', models.BooleanField(help_text='¿El inicio de sesión fue exitoso?')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que intentó iniciar sesión, si existe', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usuario')),
            ],
            options={
                'db_table': 'auditoria',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_venta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('id_cliente', models.ForeignKey(blank=True, db_column='id_cliente', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.cliente')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.usuario')),
            ],
            options={
                'db_table': 'venta',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='facturacliente',
            name='id_venta',
            field=models.ForeignKey(blank=True, db_column='id_venta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.venta'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='id_venta',
            field=models.ForeignKey(blank=True, db_column='id_venta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.venta'),
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalleventa', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('id_producto', models.ForeignKey(blank=True, db_column='id_producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.producto')),
                ('id_venta', models.ForeignKey(blank=True, db_column='id_venta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.venta')),
            ],
            options={
                'db_table': 'detalle_venta',
                'managed': True,
            },
        ),
    ]
