# Generated by Django 6.0.4 on 2026-06-06 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Correo usado para el login', max_length=100)),
                ('exito', models.BooleanField(help_text='¿El inicio de sesión fue exitoso?')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auditoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(help_text='Correo del usuario', max_length=100)),
                ('evento', models.CharField(help_text='Tipo de evento/acción realizado', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Detalle adicional', null=True)),
                ('modulo', models.CharField(blank=True, help_text='Módulo relacionado', max_length=50, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'db_table': 'auditoria_evento',
                'managed': False,
            },
        ),
    ]
