# Generated by Django 6.0.4 on 2026-06-23 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditoria_auditoriaevento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoDanado',
            fields=[
                ('id_producto_danado', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(default=1)),
                ('motivo_dano', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
                ('estado_proceso', models.CharField(db_collation='Modern_Spanish_CI_AS', default='PENDIENTE', max_length=30)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, db_collation='Modern_Spanish_CI_AS', null=True)),
            ],
            options={
                'db_table': 'producto_danado',
                'managed': False,
            },
        ),
    ]
