"""
Django settings for ferreteria project.
Generated by 'django-admin startproject' using Django 6.0.4.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

# --- CONFIGURACIÓN DE CARPETAS FÍSICAS PARA DOCUMENTOS DE LA FERRETERÍA ---
CARPETA_DOCUMENTOS_SISTEMA = BASE_DIR.parent / "Documentos_FerreteriaMicasa" 

SUBCARPETAS_FERRETERIA = {
    "Compras": CARPETA_DOCUMENTOS_SISTEMA / "Compras",
    "Ventas": CARPETA_DOCUMENTOS_SISTEMA / "Ventas",
    "Devoluciones": CARPETA_DOCUMENTOS_SISTEMA / "Devoluciones",
    "Inventarios": CARPETA_DOCUMENTOS_SISTEMA / "Inventarios",
    "Reportes": CARPETA_DOCUMENTOS_SISTEMA / "Reportes",
}

# Crear automáticamente los directorios físicos al iniciar el proyecto si no existen
for ruta in SUBCARPETAS_FERRETERIA.values():
    ruta.mkdir(parents=True, exist_ok=True)


# --- SEGURIDAD Y ENTORNO ---
# Lee SECRET_KEY del entorno .env; si no existe usa el fallback
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-pk4&u7!fgugg!h58=52x+w4qg!w4+!j$j@+d5+mvo7)f)0b*e0')

# Manejo dinámico del modo DEBUG desde el .env
DEBUG = os.getenv('DEBUG', 'True').lower() in ('true', '1', 't')

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(',')


# --- APLICACIONES INSTALADAS ---
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Aplicaciones locales del proyecto
    "apps.accounts",
    "apps.compras",
    "apps.ventas",
    "apps.registro",
    "apps.devolucion",
    "apps.core",
    "apps.cliente",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Middleware para servir archivos estáticos eficientemente
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ferreteria.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ferreteria.wsgi.application'


# --- BASE DE DATOS (SQL Server) ---
DATABASES = {
    "default": {
        "ENGINE": "mssql",
        "NAME": os.getenv("DB_NAME", "Ferreteria"),
        "HOST": os.getenv("DB_HOST", "MSI"),
        "OPTIONS": {
            "driver": os.getenv("DB_DRIVER", "ODBC Driver 17 for SQL Server"),
            "TrustServerCertificate": "yes",
        },
    }
}


# --- VALIDACIÓN DE CONTRASEÑAS ---
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# --- IDIOMA Y ZONA HORARIA ---
LANGUAGE_CODE = 'es-ni'  # Configurado a Español (Nicaragua)
TIME_ZONE = 'America/Managua'
USE_I18N = True
USE_TZ = True


# --- ARCHIVOS ESTÁTICOS Y ARCHIVOS MULTIMEDIA (MEDIA) ---
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / "static"]

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# --- SESIONES Y SEGURIDAD MULTI-USUARIO ---
SESSION_COOKIE_AGE = 60 * 60  # 60 minutos
SESSION_SAVE_EVERY_REQUEST = True  # Renueva la sesión con la actividad del usuario
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # Cierra sesión al cerrar el navegador

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "/login/"


# --- CONFIGURACIÓN DE CORREO ELECTRÓNICO ---
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "admin.ferreteria@gmail.com")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER