#```python name=ferreteria/settings.py
"""
Django settings for ferreteria project.
Generated by 'django-admin startproject' using Django 6.0.4.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

BASE_DIR = Path(__file__).resolve().parent.parent

SECRET_KEY = 'django-insecure-pk4&u7!fgugg!h58=52x+w4qg!w4+!j$j@+d5+mvo7)f)0b*e0'
DEBUG = True
ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "apps.accounts",
    "apps.compras",
    "apps.ventas",
    "apps.registro",
    "apps.devolucion",
    "apps.core",
    "apps.cliente",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ferreteria.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ferreteria.wsgi.application'

# DB_HOST debe incluir servidor e instancia, por ejemplo: MSI\SQLEXPRESS o .\SQLEXPRESS.
db_host = os.getenv("DB_HOST", r"MARCEL-TM\SQLEXPRESS")
if db_host == "MARCEL-TM\SQLEXPRESS":
    db_host = r"MARCEL-TM\SQLEXPRESS"

# DATABASE (SQL Server)
DATABASES = {
    "default": {
        "ENGINE": "mssql",
        "NAME": os.getenv("DB_NAME", "Ferreteria"),
        "HOST": db_host,
        "OPTIONS": {
            "driver": "ODBC Driver 17 for SQL Server",
            "TrustServerCertificate": "yes",
        },
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / "static"]

# --- Sesiones / Seguridad multi-usuario (CRÍTICO) ---
# 10-15 minutos suele ser bueno para cajas / POS
SESSION_COOKIE_AGE = 60 * 60  # 60 minutos
SESSION_SAVE_EVERY_REQUEST = True  # renueva el timeout con actividad (inactividad real)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True  # al cerrar navegador pide login otra vez

# Recomendado en producción (HTTPS):
# SESSION_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "dashboard"
LOGOUT_REDIRECT_URL = "/login/"

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_HOST_USER = "admin.ferreteria@gmail.com"          # ← El correo creado para la app
EMAIL_HOST_PASSWORD = "uyqvcbecqmrcawsr"     # ← La contraseña de aplicación
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER